on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hi anji"
        shell:bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: hi rajat and pradip
        run: echo "hi rajat and pradip"
        shell:bash
